name: hugo publish
 
on:
  push:
    branches: [ master ]
 
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Update theme
        run: git submodule update --init --recursive
 
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
 
      - name: Build
        run: hugo  --minify
 
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          external_repository: ahito89/ahito89.github.io
          publish_branch: master
          publish_dir: ./public
          user_name: Ionut Duma
          user_email: ionutduma@hotmail.com
          keep_files: true
